# Generated by Django 2.1.5 on 2019-02-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
